### ISSUE TITLE
Solutions for Ex 10, 11 and 12

### ISSUE THREAD

**Issue by ghost** [HandsOnOpenCL/Lecture-Slides#29]
¿Does anyone have the solutions for exercises 10,11 and 12?

**Comment by tomdeakin** [comment]
There are no solutions provided because there are examples in SDKs or the exercise is just "try things out".

Exercise 10 suggests targeting multiple devices within a single context. All the vendor OpenCL SDKs provide examples of this.

Exercise 11 suggests taking something like the solution to Exercise 8 and making it work well on both CPUs and GPUs.

Exercise 12 suggests experimenting with one of the profile tools using any OpenCL code you like.
